
version: 2
sources:
  - name: my_raw
    database : yogesh
    schema: sakshi
    tables:
      - name: transactions
      - name: tuser
      - name: marchant
      - name: payment             
