version: 2

version: 2

sources:
  - name: yogesh
    database: banking_db
    schema: bank
    tables:
      - name: customers
        columns:
          - name: CUSTOMER_ID
            tests:
              - not_null
              - unique

      - name: payments
        columns:
          - name: PAYMENT_ID
            tests:
              - not_null
              - unique



    
